# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      continue-on-error: true
      with:
        node-version: 14.x
    - run: curl -sSL git.io/zoe-site | bash
    - run: cp -r /tmp/zoe-site/gatsby-starter-zoe-app/public .
    - run: cp CNAME public/ || true
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: hi@zoe.im
        build_dir: public